
//! Autogenerated weights for `ring_sig`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-11-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-EGPK2MH`, CPU: `12th Gen Intel(R) Core(TM) i7-12700H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/sqfzy/.cargo/bin/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/parachain-template-runtime/parachain_template_runtime.wasm
// --pallet
// ring_sig
// --extrinsic
// 
// --template
// ./pallets/ring_sig/frame-weight-template.hbs
// --output
// ./pallets/ring_sig/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::deps::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `ring_sig`.
pub trait WeightInfo {
	fn create_proposal() -> Weight;
	fn close_proposal() -> Weight;
	fn anonymous_vote() -> Weight;
}

/// Weights for `ring_sig` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame::deps::frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `RingSig::ProposalCount` (r:1 w:1)
	/// Proof: `RingSig::ProposalCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `RingSig::ProposalVotes` (r:0 w:1)
	/// Proof: `RingSig::ProposalVotes` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `RingSig::Proposals` (r:0 w:1)
	/// Proof: `RingSig::Proposals` (`max_values`: None, `max_size`: Some(303), added: 2778, mode: `MaxEncodedLen`)
	fn create_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `1489`
		// Minimum execution time: 6_586_000 picoseconds.
		Weight::from_parts(7_144_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSig::Proposals` (r:1 w:1)
	/// Proof: `RingSig::Proposals` (`max_values`: None, `max_size`: Some(303), added: 2778, mode: `MaxEncodedLen`)
	fn close_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `3768`
		// Minimum execution time: 7_856_000 picoseconds.
		Weight::from_parts(8_054_000, 3768)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSig::Proposals` (r:1 w:0)
	/// Proof: `RingSig::Proposals` (`max_values`: None, `max_size`: Some(303), added: 2778, mode: `MaxEncodedLen`)
	/// Storage: `RingSig::UsedKeyImages` (r:1 w:1)
	/// Proof: `RingSig::UsedKeyImages` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `RingSig::ProposalVotes` (r:1 w:1)
	/// Proof: `RingSig::ProposalVotes` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn anonymous_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `230`
		//  Estimated: `3768`
		// Minimum execution time: 12_734_225_000 picoseconds.
		Weight::from_parts(13_143_983_000, 3768)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `RingSig::ProposalCount` (r:1 w:1)
	/// Proof: `RingSig::ProposalCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `RingSig::ProposalVotes` (r:0 w:1)
	/// Proof: `RingSig::ProposalVotes` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `RingSig::Proposals` (r:0 w:1)
	/// Proof: `RingSig::Proposals` (`max_values`: None, `max_size`: Some(303), added: 2778, mode: `MaxEncodedLen`)
	fn create_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `1489`
		// Minimum execution time: 6_586_000 picoseconds.
		Weight::from_parts(7_144_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSig::Proposals` (r:1 w:1)
	/// Proof: `RingSig::Proposals` (`max_values`: None, `max_size`: Some(303), added: 2778, mode: `MaxEncodedLen`)
	fn close_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `3768`
		// Minimum execution time: 7_856_000 picoseconds.
		Weight::from_parts(8_054_000, 3768)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSig::Proposals` (r:1 w:0)
	/// Proof: `RingSig::Proposals` (`max_values`: None, `max_size`: Some(303), added: 2778, mode: `MaxEncodedLen`)
	/// Storage: `RingSig::UsedKeyImages` (r:1 w:1)
	/// Proof: `RingSig::UsedKeyImages` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `RingSig::ProposalVotes` (r:1 w:1)
	/// Proof: `RingSig::ProposalVotes` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn anonymous_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `230`
		//  Estimated: `3768`
		// Minimum execution time: 12_734_225_000 picoseconds.
		Weight::from_parts(13_143_983_000, 3768)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
