
//! Autogenerated weights for `ring_sig`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-11-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-EGPK2MH`, CPU: `12th Gen Intel(R) Core(TM) i7-12700H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/sqfzy/.cargo/bin/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/parachain-template-runtime/parachain_template_runtime.wasm
// --pallet
// ring_sig
// --extrinsic
// anonymous_vote
// --template
// ./pallets/ring_sig/frame-weight-template.hbs
// --output
// ./pallets/ring_sig/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for `ring_sig`.
pub trait WeightInfo {
	fn anonymous_vote() -> Weight;
}

/// Weights for `ring_sig` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `RingSig::UsedKeyImages` (r:1 w:1)
	/// Proof: `RingSig::UsedKeyImages` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `RingSig::ProposalVotes` (r:1 w:1)
	/// Proof: `RingSig::ProposalVotes` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn anonymous_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3533`
		// Minimum execution time: 13_299_761_000 picoseconds.
		Weight::from_parts(14_349_570_000, 3533)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `RingSig::UsedKeyImages` (r:1 w:1)
	/// Proof: `RingSig::UsedKeyImages` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `RingSig::ProposalVotes` (r:1 w:1)
	/// Proof: `RingSig::ProposalVotes` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn anonymous_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3533`
		// Minimum execution time: 13_299_761_000 picoseconds.
		Weight::from_parts(14_349_570_000, 3533)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
