[package]
name = "ring_sig_voting"
version = "0.1.0"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
frame = { features = ["experimental", "runtime"], workspace = true }
nazgul = { version = "2.1", default-features = false, features = ["no_std"] }
curve25519-dalek = { version = "4.1.3", default-features = false }
# sha2 = { version = "0.10.9", default-features = false }
rand_core = { version = "0.6.4", default-features = false }
# rand_chacha = { version = "0.3", default-features = false }
getrandom = { version = "0.2", default-features = false, features = ["custom"] }
primitive-types = { version = "0.14", default-features = false, features = [
  "codec",
  "scale-info",
] }

ark-serialize = { version = "0.3", features = [
  "derive",
], default-features = false }
ark-ff = { version = "0.3", default-features = false }
ark-ec = { version = "0.3", default-features = false }
ark-std = { version = "0.3", default-features = false }
# ark-groth16 = { version = "0.3", features = ["r1cs"], default-features = false }
# ark-bn254 = { version = "0.5", default-features = false }
# ark-bls12-381 = {version = "0.5", default-features = false }
ark-bls12-381 = { version = "0.3", features = [
  "curve",
], default-features = false }
ark-relations = { version = "0.3", default-features = false }
ark-snark = { version = "0.3", default-features = false }
ark-marlin = { version = "0.3", default-features = false }
ark-poly = { version = "0.3", default-features = false }
ark-poly-commit = { version = "0.3", default-features = false }
rand_chacha = { version = "0.3", default-features = false }
blake2 = { version = "0.9", default-features = false }

[dev-dependencies]
polkadot-sdk = { workspace = true, default-features = false, features = [
  # "pallet-balances",
  "pallet-preimage",
  "pallet-scheduler",
] }

[features]
default = ["std"]
runtime-benchmarks = [
  "frame/runtime-benchmarks",
  "polkadot-sdk/runtime-benchmarks",
]
std = [
  "codec/std",
  "frame/std",
  "scale-info/std",
  "nazgul/std",
  "getrandom/std",
  "polkadot-sdk/std",
  "ark-serialize/std",
  "ark-ff/std",
  "ark-ec/std",
  "ark-std/std",
  "ark-marlin/std",
  "ark-bls12-381/std",
  "ark-relations/std",
]
