//! Autogenerated weights for pallet_anonymous_voting
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0. 0
//! DATE: 2025-01-01
//! STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//!  HOSTNAME: `benchmark-host`, CPU: `Intel(R) Core(TM) i7-10700K CPU @ 3. 80GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_anonymous_voting. 
pub trait WeightInfo {
    fn register_ring_group(n: u32) -> Weight;
    fn create_poll() -> Weight;
    fn vote(n: u32) -> Weight;
    fn tally() -> Weight;
    fn cancel_poll() -> Weight;
    fn pause_poll() -> Weight;
    fn resume_poll() -> Weight;
    fn set_deadline() -> Weight;
}

/// Weights for pallet_anonymous_voting using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `AnonymousVoting::RingCount` (r:1 w:1)
    /// Storage: `AnonymousVoting::Rings` (r:0 w:1)
    /// The range of component `n` is `[1, 256]`.
    fn register_ring_group(n: u32) -> Weight {
        Weight::from_parts(15_000_000, 5000)
            .saturating_add(Weight::from_parts(500_000, 0). saturating_mul(n. into()))
            .saturating_add(T::DbWeight::get().reads(1_u64))
            . saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `AnonymousVoting::Rings` (r:1 w:0)
    /// Storage: `AnonymousVoting::PollCount` (r:1 w:1)
    /// Storage: `AnonymousVoting::Polls` (r:0 w:1)
    /// Storage: `AnonymousVoting::TallyVks` (r:0 w:1)
    fn create_poll() -> Weight {
        Weight::from_parts(25_000_000, 7000)
            . saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }

    /// Storage: `AnonymousVoting::Polls` (r:1 w:1)
    /// Storage: `AnonymousVoting::Rings` (r:1 w:0)
    /// Storage: `AnonymousVoting::UsedKeyImages` (r:1 w:1)
    /// Storage: `AnonymousVoting::EncryptedVotes` (r:1 w:1)
    /// The range of component `n` is `[1, 256]`. 
    fn vote(n: u32) -> Weight {
        Weight::from_parts(100_000_000, 10000)
            .saturating_add(Weight::from_parts(5_000_000, 0).saturating_mul(n. into()))
            . saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }

    /// Storage: `AnonymousVoting::Polls` (r:1 w:1)
    /// Storage: `AnonymousVoting::TallyVks` (r:1 w:0)
    /// Storage: `AnonymousVoting::EncryptedVotes` (r:1 w:0)
    /// Storage: `AnonymousVoting::Tallies` (r:0 w:1)
    fn tally() -> Weight {
        Weight::from_parts(5_000_000_000, 50000)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `AnonymousVoting::Polls` (r:1 w:1)
    fn cancel_poll() -> Weight {
        Weight::from_parts(10_000_000, 3000)
            . saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `AnonymousVoting::Polls` (r:1 w:1)
    fn pause_poll() -> Weight {
        Weight::from_parts(10_000_000, 3000)
            .saturating_add(T::DbWeight::get(). reads(1_u64))
            . saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `AnonymousVoting::Polls` (r:1 w:1)
    fn resume_poll() -> Weight {
        Weight::from_parts(10_000_000, 3000)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `AnonymousVoting::Polls` (r:1 w:1)
    fn set_deadline() -> Weight {
        Weight::from_parts(10_000_000, 3000)
            .saturating_add(T::DbWeight::get(). reads(1_u64))
            . saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

// For tests
impl WeightInfo for () {
    fn register_ring_group(n: u32) -> Weight {
        Weight::from_parts(15_000_000, 5000)
            .saturating_add(Weight::from_parts(500_000, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get(). writes(2_u64))
    }

    fn create_poll() -> Weight {
        Weight::from_parts(25_000_000, 7000)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }

    fn vote(n: u32) -> Weight {
        Weight::from_parts(100_000_000, 10000)
            .saturating_add(Weight::from_parts(5_000_000, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }

    fn tally() -> Weight {
        Weight::from_parts(5_000_000_000, 50000)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get(). writes(2_u64))
    }

    fn cancel_poll() -> Weight {
        Weight::from_parts(10_000_000, 3000)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn pause_poll() -> Weight {
        Weight::from_parts(10_000_000, 3000)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn resume_poll() -> Weight {
        Weight::from_parts(10_000_000, 3000)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get(). writes(1_u64))
    }

    fn set_deadline() -> Weight {
        Weight::from_parts(10_000_000, 3000)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}
