
//! Autogenerated weights for `ring_sig_voting`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2026-04-05, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-EGPK2MH`, CPU: `12th Gen Intel(R) Core(TM) i7-12700H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/sqfzy/.cargo/bin/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/parachain-template-runtime/parachain_template_runtime.wasm
// --pallet
// ring_sig_voting
// --extrinsic
// 
// --template
// ./pallets/ring_sig_voting/frame-weight-template.hbs
// --output
// ./pallets/ring_sig_voting/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `ring_sig_voting`.
pub trait WeightInfo {
	fn register_ring() -> Weight;
	fn create_poll() -> Weight;
	fn vote() -> Weight;
	fn tally_poll() -> Weight;
	fn cancel_poll() -> Weight;
	fn pause_poll() -> Weight;
	fn active_poll() -> Weight;
	fn set_deadline() -> Weight;
	fn tally() -> Weight;
	fn authorize_teacher() -> Weight;
	fn revoke_teacher() -> Weight;
	fn change_owner() -> Weight;
}

/// Weights for `ring_sig_voting` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `RingSigVoting::StudentKeys` (r:30 w:0)
	/// Proof: `RingSigVoting::StudentKeys` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::RingCount` (r:1 w:1)
	/// Proof: `RingSigVoting::RingCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Rings` (r:0 w:1)
	/// Proof: `RingSigVoting::Rings` (`max_values`: None, `max_size`: Some(1045), added: 3520, mode: `MaxEncodedLen`)
	fn register_ring() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1833`
		//  Estimated: `76800`
		// Minimum execution time: 181_552_000 picoseconds.
		Weight::from_parts(228_461_000, 76800)
			.saturating_add(T::DbWeight::get().reads(31_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `RingSigVoting::Teachers` (r:1 w:0)
	/// Proof: `RingSigVoting::Teachers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Rings` (r:1 w:0)
	/// Proof: `RingSigVoting::Rings` (`max_values`: None, `max_size`: Some(1045), added: 3520, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollCount` (r:1 w:1)
	/// Proof: `RingSigVoting::PollCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::StatusFor` (r:1 w:0)
	/// Proof: `Preimage::StatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::RequestStatusFor` (r:1 w:1)
	/// Proof: `Preimage::RequestStatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Polls` (r:0 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::PreimageFor` (r:0 w:1)
	/// Proof: `Preimage::PreimageFor` (`max_values`: None, `max_size`: Some(4194344), added: 4196819, mode: `MaxEncodedLen`)
	fn create_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `312`
		//  Estimated: `402327`
		// Minimum execution time: 89_105_000 picoseconds.
		Weight::from_parts(131_785_000, 402327)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:0)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::UsedKeyImages` (r:1 w:1)
	/// Proof: `RingSigVoting::UsedKeyImages` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Rings` (r:1 w:0)
	/// Proof: `RingSigVoting::Rings` (`max_values`: None, `max_size`: Some(1045), added: 3520, mode: `MaxEncodedLen`)
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::EncryptedVotes` (r:1 w:1)
	/// Proof: `RingSigVoting::EncryptedVotes` (`max_values`: None, `max_size`: Some(194022), added: 196497, mode: `MaxEncodedLen`)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1395`
		//  Estimated: `197487`
		// Minimum execution time: 20_006_937_000 picoseconds.
		Weight::from_parts(27_273_776_000, 197487)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn tally_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `503`
		//  Estimated: `402327`
		// Minimum execution time: 49_421_000 picoseconds.
		Weight::from_parts(59_692_000, 402327)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn cancel_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `503`
		//  Estimated: `402327`
		// Minimum execution time: 52_275_000 picoseconds.
		Weight::from_parts(101_772_000, 402327)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn pause_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `503`
		//  Estimated: `402327`
		// Minimum execution time: 51_279_000 picoseconds.
		Weight::from_parts(115_028_000, 402327)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn active_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `348`
		//  Estimated: `402327`
		// Minimum execution time: 54_637_000 picoseconds.
		Weight::from_parts(105_879_000, 402327)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:2 w:2)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn set_deadline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `503`
		//  Estimated: `803664`
		// Minimum execution time: 70_695_000 picoseconds.
		Weight::from_parts(122_937_000, 803664)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	fn tally() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `345`
		//  Estimated: `4912`
		// Minimum execution time: 104_604_000 picoseconds.
		Weight::from_parts(137_186_000, 4912)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSigVoting::Teachers` (r:1 w:1)
	/// Proof: `RingSigVoting::Teachers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn authorize_teacher() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3513`
		// Minimum execution time: 13_244_000 picoseconds.
		Weight::from_parts(15_291_000, 3513)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSigVoting::Teachers` (r:1 w:1)
	/// Proof: `RingSigVoting::Teachers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn revoke_teacher() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `150`
		//  Estimated: `3513`
		// Minimum execution time: 31_396_000 picoseconds.
		Weight::from_parts(50_400_000, 3513)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	fn change_owner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `345`
		//  Estimated: `4912`
		// Minimum execution time: 24_947_000 picoseconds.
		Weight::from_parts(53_724_000, 4912)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `RingSigVoting::StudentKeys` (r:30 w:0)
	/// Proof: `RingSigVoting::StudentKeys` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::RingCount` (r:1 w:1)
	/// Proof: `RingSigVoting::RingCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Rings` (r:0 w:1)
	/// Proof: `RingSigVoting::Rings` (`max_values`: None, `max_size`: Some(1045), added: 3520, mode: `MaxEncodedLen`)
	fn register_ring() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1833`
		//  Estimated: `76800`
		// Minimum execution time: 181_552_000 picoseconds.
		Weight::from_parts(228_461_000, 76800)
			.saturating_add(RocksDbWeight::get().reads(31_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `RingSigVoting::Teachers` (r:1 w:0)
	/// Proof: `RingSigVoting::Teachers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Rings` (r:1 w:0)
	/// Proof: `RingSigVoting::Rings` (`max_values`: None, `max_size`: Some(1045), added: 3520, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollCount` (r:1 w:1)
	/// Proof: `RingSigVoting::PollCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::StatusFor` (r:1 w:0)
	/// Proof: `Preimage::StatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::RequestStatusFor` (r:1 w:1)
	/// Proof: `Preimage::RequestStatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Polls` (r:0 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::PreimageFor` (r:0 w:1)
	/// Proof: `Preimage::PreimageFor` (`max_values`: None, `max_size`: Some(4194344), added: 4196819, mode: `MaxEncodedLen`)
	fn create_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `312`
		//  Estimated: `402327`
		// Minimum execution time: 89_105_000 picoseconds.
		Weight::from_parts(131_785_000, 402327)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:0)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::UsedKeyImages` (r:1 w:1)
	/// Proof: `RingSigVoting::UsedKeyImages` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Rings` (r:1 w:0)
	/// Proof: `RingSigVoting::Rings` (`max_values`: None, `max_size`: Some(1045), added: 3520, mode: `MaxEncodedLen`)
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::EncryptedVotes` (r:1 w:1)
	/// Proof: `RingSigVoting::EncryptedVotes` (`max_values`: None, `max_size`: Some(194022), added: 196497, mode: `MaxEncodedLen`)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1395`
		//  Estimated: `197487`
		// Minimum execution time: 20_006_937_000 picoseconds.
		Weight::from_parts(27_273_776_000, 197487)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn tally_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `503`
		//  Estimated: `402327`
		// Minimum execution time: 49_421_000 picoseconds.
		Weight::from_parts(59_692_000, 402327)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn cancel_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `503`
		//  Estimated: `402327`
		// Minimum execution time: 52_275_000 picoseconds.
		Weight::from_parts(101_772_000, 402327)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn pause_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `503`
		//  Estimated: `402327`
		// Minimum execution time: 51_279_000 picoseconds.
		Weight::from_parts(115_028_000, 402327)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn active_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `348`
		//  Estimated: `402327`
		// Minimum execution time: 54_637_000 picoseconds.
		Weight::from_parts(105_879_000, 402327)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:2 w:2)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn set_deadline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `503`
		//  Estimated: `803664`
		// Minimum execution time: 70_695_000 picoseconds.
		Weight::from_parts(122_937_000, 803664)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	fn tally() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `345`
		//  Estimated: `4912`
		// Minimum execution time: 104_604_000 picoseconds.
		Weight::from_parts(137_186_000, 4912)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSigVoting::Teachers` (r:1 w:1)
	/// Proof: `RingSigVoting::Teachers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn authorize_teacher() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3513`
		// Minimum execution time: 13_244_000 picoseconds.
		Weight::from_parts(15_291_000, 3513)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSigVoting::Teachers` (r:1 w:1)
	/// Proof: `RingSigVoting::Teachers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn revoke_teacher() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `150`
		//  Estimated: `3513`
		// Minimum execution time: 31_396_000 picoseconds.
		Weight::from_parts(50_400_000, 3513)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	fn change_owner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `345`
		//  Estimated: `4912`
		// Minimum execution time: 24_947_000 picoseconds.
		Weight::from_parts(53_724_000, 4912)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
