
//! Autogenerated weights for `ring_sig_voting`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2026-01-19, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-EGPK2MH`, CPU: `12th Gen Intel(R) Core(TM) i7-12700H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/sqfzy/.cargo/bin/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/parachain-template-runtime/parachain_template_runtime.wasm
// --pallet
// ring_sig_voting
// --extrinsic
// 
// --template
// ./pallets/ring_sig_voting/frame-weight-template.hbs
// --output
// ./pallets/ring_sig_voting/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::deps::frame_support;
use frame::deps::frame_system;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `ring_sig_voting`.
pub trait WeightInfo {
	fn register_ring() -> Weight;
	fn create_poll() -> Weight;
	fn vote() -> Weight;
	fn tally_poll() -> Weight;
	fn cancel_poll() -> Weight;
	fn pause_poll() -> Weight;
	fn active_poll() -> Weight;
	fn set_deadline() -> Weight;
	fn tally() -> Weight;
	fn authorize_teacher() -> Weight;
	fn revoke_teacher() -> Weight;
	fn change_owner() -> Weight;
}

/// Weights for `ring_sig_voting` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `RingSigVoting::RingCount` (r:1 w:1)
	/// Proof: `RingSigVoting::RingCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Rings` (r:0 w:1)
	/// Proof: `RingSigVoting::Rings` (`max_values`: None, `max_size`: Some(533), added: 3008, mode: `MaxEncodedLen`)
	fn register_ring() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `1489`
		// Minimum execution time: 7_039_000 picoseconds.
		Weight::from_parts(8_139_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `RingSigVoting::Teachers` (r:1 w:0)
	/// Proof: `RingSigVoting::Teachers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Rings` (r:1 w:0)
	/// Proof: `RingSigVoting::Rings` (`max_values`: None, `max_size`: Some(533), added: 3008, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollCount` (r:1 w:1)
	/// Proof: `RingSigVoting::PollCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::StatusFor` (r:1 w:0)
	/// Proof: `Preimage::StatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::RequestStatusFor` (r:1 w:1)
	/// Proof: `Preimage::RequestStatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Polls` (r:0 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::PreimageFor` (r:0 w:1)
	/// Proof: `Preimage::PreimageFor` (`max_values`: None, `max_size`: Some(4194344), added: 4196819, mode: `MaxEncodedLen`)
	fn create_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `256`
		//  Estimated: `402327`
		// Minimum execution time: 41_484_000 picoseconds.
		Weight::from_parts(62_320_000, 402327)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:0)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::UsedKeyImages` (r:1 w:1)
	/// Proof: `RingSigVoting::UsedKeyImages` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Rings` (r:1 w:0)
	/// Proof: `RingSigVoting::Rings` (`max_values`: None, `max_size`: Some(533), added: 3008, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::EncryptedVotes` (r:1 w:1)
	/// Proof: `RingSigVoting::EncryptedVotes` (`max_values`: None, `max_size`: Some(194022), added: 196497, mode: `MaxEncodedLen`)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `670`
		//  Estimated: `197487`
		// Minimum execution time: 3_701_394_000 picoseconds.
		Weight::from_parts(3_860_816_000, 197487)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn tally_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `470`
		//  Estimated: `402327`
		// Minimum execution time: 22_133_000 picoseconds.
		Weight::from_parts(23_713_000, 402327)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn cancel_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `470`
		//  Estimated: `402327`
		// Minimum execution time: 21_180_000 picoseconds.
		Weight::from_parts(23_154_000, 402327)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn pause_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `470`
		//  Estimated: `402327`
		// Minimum execution time: 21_707_000 picoseconds.
		Weight::from_parts(25_247_000, 402327)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn active_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315`
		//  Estimated: `402327`
		// Minimum execution time: 20_506_000 picoseconds.
		Weight::from_parts(24_138_000, 402327)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:2 w:2)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn set_deadline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `470`
		//  Estimated: `803664`
		// Minimum execution time: 32_977_000 picoseconds.
		Weight::from_parts(35_691_000, 803664)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	fn tally() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `312`
		//  Estimated: `4912`
		// Minimum execution time: 55_487_000 picoseconds.
		Weight::from_parts(58_082_000, 4912)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSigVoting::Teachers` (r:1 w:1)
	/// Proof: `RingSigVoting::Teachers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn authorize_teacher() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3513`
		// Minimum execution time: 7_826_000 picoseconds.
		Weight::from_parts(8_509_000, 3513)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSigVoting::Teachers` (r:1 w:1)
	/// Proof: `RingSigVoting::Teachers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn revoke_teacher() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `150`
		//  Estimated: `3513`
		// Minimum execution time: 9_650_000 picoseconds.
		Weight::from_parts(10_066_000, 3513)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	fn change_owner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `312`
		//  Estimated: `4912`
		// Minimum execution time: 9_818_000 picoseconds.
		Weight::from_parts(12_941_000, 4912)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `RingSigVoting::RingCount` (r:1 w:1)
	/// Proof: `RingSigVoting::RingCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Rings` (r:0 w:1)
	/// Proof: `RingSigVoting::Rings` (`max_values`: None, `max_size`: Some(533), added: 3008, mode: `MaxEncodedLen`)
	fn register_ring() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `1489`
		// Minimum execution time: 7_039_000 picoseconds.
		Weight::from_parts(8_139_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `RingSigVoting::Teachers` (r:1 w:0)
	/// Proof: `RingSigVoting::Teachers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Rings` (r:1 w:0)
	/// Proof: `RingSigVoting::Rings` (`max_values`: None, `max_size`: Some(533), added: 3008, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollCount` (r:1 w:1)
	/// Proof: `RingSigVoting::PollCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::StatusFor` (r:1 w:0)
	/// Proof: `Preimage::StatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::RequestStatusFor` (r:1 w:1)
	/// Proof: `Preimage::RequestStatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Polls` (r:0 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Preimage::PreimageFor` (r:0 w:1)
	/// Proof: `Preimage::PreimageFor` (`max_values`: None, `max_size`: Some(4194344), added: 4196819, mode: `MaxEncodedLen`)
	fn create_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `256`
		//  Estimated: `402327`
		// Minimum execution time: 41_484_000 picoseconds.
		Weight::from_parts(62_320_000, 402327)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:0)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::UsedKeyImages` (r:1 w:1)
	/// Proof: `RingSigVoting::UsedKeyImages` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Rings` (r:1 w:0)
	/// Proof: `RingSigVoting::Rings` (`max_values`: None, `max_size`: Some(533), added: 3008, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::EncryptedVotes` (r:1 w:1)
	/// Proof: `RingSigVoting::EncryptedVotes` (`max_values`: None, `max_size`: Some(194022), added: 196497, mode: `MaxEncodedLen`)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `670`
		//  Estimated: `197487`
		// Minimum execution time: 3_701_394_000 picoseconds.
		Weight::from_parts(3_860_816_000, 197487)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn tally_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `470`
		//  Estimated: `402327`
		// Minimum execution time: 22_133_000 picoseconds.
		Weight::from_parts(23_713_000, 402327)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn cancel_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `470`
		//  Estimated: `402327`
		// Minimum execution time: 21_180_000 picoseconds.
		Weight::from_parts(23_154_000, 402327)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn pause_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `470`
		//  Estimated: `402327`
		// Minimum execution time: 21_707_000 picoseconds.
		Weight::from_parts(25_247_000, 402327)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn active_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315`
		//  Estimated: `402327`
		// Minimum execution time: 20_506_000 picoseconds.
		Weight::from_parts(24_138_000, 402327)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:2 w:2)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(398862), added: 401337, mode: `MaxEncodedLen`)
	fn set_deadline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `470`
		//  Estimated: `803664`
		// Minimum execution time: 32_977_000 picoseconds.
		Weight::from_parts(35_691_000, 803664)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	fn tally() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `312`
		//  Estimated: `4912`
		// Minimum execution time: 55_487_000 picoseconds.
		Weight::from_parts(58_082_000, 4912)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSigVoting::Teachers` (r:1 w:1)
	/// Proof: `RingSigVoting::Teachers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn authorize_teacher() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3513`
		// Minimum execution time: 7_826_000 picoseconds.
		Weight::from_parts(8_509_000, 3513)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSigVoting::Teachers` (r:1 w:1)
	/// Proof: `RingSigVoting::Teachers` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn revoke_teacher() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `150`
		//  Estimated: `3513`
		// Minimum execution time: 9_650_000 picoseconds.
		Weight::from_parts(10_066_000, 3513)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(1447), added: 3922, mode: `MaxEncodedLen`)
	fn change_owner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `312`
		//  Estimated: `4912`
		// Minimum execution time: 9_818_000 picoseconds.
		Weight::from_parts(12_941_000, 4912)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
