
//! Autogenerated weights for `ring_sig_voting`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-11-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-EGPK2MH`, CPU: `12th Gen Intel(R) Core(TM) i7-12700H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/sqfzy/.cargo/bin/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/parachain-template-runtime/parachain_template_runtime.wasm
// --pallet
// ring_sig_voting
// --extrinsic
// 
// --template
// ./pallets/ring_sig_voting/frame-weight-template.hbs
// --output
// ./pallets/ring_sig_voting/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::deps::frame_support;
use frame::deps::frame_system;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `ring_sig_voting`.
pub trait WeightInfo {
	fn register_ring_group() -> Weight;
	fn create_poll() -> Weight;
	fn close_poll() -> Weight;
	fn anonymous_vote() -> Weight;
}

/// Weights for `ring_sig_voting` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `RingSigVoting::RingGroupCount` (r:1 w:1)
	/// Proof: `RingSigVoting::RingGroupCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::RingGroups` (r:0 w:1)
	/// Proof: `RingSigVoting::RingGroups` (`max_values`: None, `max_size`: Some(1057), added: 3532, mode: `MaxEncodedLen`)
	fn register_ring_group() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `1493`
		// Minimum execution time: 9_287_000 picoseconds.
		Weight::from_parts(11_078_000, 1493)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `RingSigVoting::RingGroups` (r:1 w:0)
	/// Proof: `RingSigVoting::RingGroups` (`max_values`: None, `max_size`: Some(1057), added: 3532, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollCount` (r:1 w:1)
	/// Proof: `RingSigVoting::PollCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollVotes` (r:0 w:1)
	/// Proof: `RingSigVoting::PollVotes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollRingId` (r:0 w:1)
	/// Proof: `RingSigVoting::PollRingId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Polls` (r:0 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn create_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `177`
		//  Estimated: `4522`
		// Minimum execution time: 22_155_000 picoseconds.
		Weight::from_parts(24_732_000, 4522)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollMetadata` (r:0 w:1)
	/// Proof: `RingSigVoting::PollMetadata` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollRingId` (r:0 w:1)
	/// Proof: `RingSigVoting::PollRingId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn close_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `335`
		//  Estimated: `3820`
		// Minimum execution time: 19_995_000 picoseconds.
		Weight::from_parts(24_158_000, 3820)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:0)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollRingId` (r:1 w:0)
	/// Proof: `RingSigVoting::PollRingId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::RingGroups` (r:1 w:0)
	/// Proof: `RingSigVoting::RingGroups` (`max_values`: None, `max_size`: Some(1057), added: 3532, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::UsedKeyImages` (r:1 w:1)
	/// Proof: `RingSigVoting::UsedKeyImages` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollVotes` (r:1 w:1)
	/// Proof: `RingSigVoting::PollVotes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn anonymous_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1436`
		//  Estimated: `4522`
		// Minimum execution time: 12_250_589_000 picoseconds.
		Weight::from_parts(12_753_504_000, 4522)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `RingSigVoting::RingGroupCount` (r:1 w:1)
	/// Proof: `RingSigVoting::RingGroupCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::RingGroups` (r:0 w:1)
	/// Proof: `RingSigVoting::RingGroups` (`max_values`: None, `max_size`: Some(1057), added: 3532, mode: `MaxEncodedLen`)
	fn register_ring_group() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `1493`
		// Minimum execution time: 9_287_000 picoseconds.
		Weight::from_parts(11_078_000, 1493)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `RingSigVoting::RingGroups` (r:1 w:0)
	/// Proof: `RingSigVoting::RingGroups` (`max_values`: None, `max_size`: Some(1057), added: 3532, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollCount` (r:1 w:1)
	/// Proof: `RingSigVoting::PollCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollVotes` (r:0 w:1)
	/// Proof: `RingSigVoting::PollVotes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollRingId` (r:0 w:1)
	/// Proof: `RingSigVoting::PollRingId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::Polls` (r:0 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn create_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `177`
		//  Estimated: `4522`
		// Minimum execution time: 22_155_000 picoseconds.
		Weight::from_parts(24_732_000, 4522)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:1)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollMetadata` (r:0 w:1)
	/// Proof: `RingSigVoting::PollMetadata` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollRingId` (r:0 w:1)
	/// Proof: `RingSigVoting::PollRingId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn close_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `335`
		//  Estimated: `3820`
		// Minimum execution time: 19_995_000 picoseconds.
		Weight::from_parts(24_158_000, 3820)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `RingSigVoting::Polls` (r:1 w:0)
	/// Proof: `RingSigVoting::Polls` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollRingId` (r:1 w:0)
	/// Proof: `RingSigVoting::PollRingId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::RingGroups` (r:1 w:0)
	/// Proof: `RingSigVoting::RingGroups` (`max_values`: None, `max_size`: Some(1057), added: 3532, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::UsedKeyImages` (r:1 w:1)
	/// Proof: `RingSigVoting::UsedKeyImages` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `RingSigVoting::PollVotes` (r:1 w:1)
	/// Proof: `RingSigVoting::PollVotes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn anonymous_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1436`
		//  Estimated: `4522`
		// Minimum execution time: 12_250_589_000 picoseconds.
		Weight::from_parts(12_753_504_000, 4522)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
